name: Update Age in README

on:
  schedule:
    - cron: '0 0 28 9 *'  # Se déclenche chaque 28 septembre à minuit UTC
  workflow_dispatch:  # Permet de déclencher manuellement le workflow

jobs:
  update-age:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Calculate and update age
      run: |
        python -c "
        import re
        from datetime import datetime

        birth_date = datetime(1989, 9, 28)
        today = datetime.now()
        age = today.year - birth_date.year - ((today.month, today.day) < (birth_date.month, birth_date.day))

        with open('README.md', 'r') as file:
            readme_content = file.read()

        pattern = r"I'm Andy, \d+ years old"
        new_content = re.sub(pattern, f'I\'m Andy, {age} years old', readme_content)

        with open('README.md', 'w') as file:
            file.write(new_content)
        "

    - name: Commit changes
      run: |
        git config --global user.name 'GitHubActionBot'
        git config --global user.email 'action-bot@github.com'
        git add README.md
        git commit -m 'Updated age in README'
        git push origin master
